services:
    database:
        image: mariadb:10.8.3
        container_name: bulasik-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3316:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bulasik-phpmyadmin
        depends_on:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: root
        restart: always
        ports:
            - 8030:80

    adminer:
        image: adminer
        container_name: bulasik-adminer
        restart: always
        ports:
            - 8040:8080
